name: rolling

on:
  pull_request:
    branches:
      - rolling
  push:
    branches:
      - rolling

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:rolling-desktop
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            wget \
            python3-vcstool \
            python3-colcon-coveragepy-result \
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: rolling
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.0
        with:
          import-token: ${{ secrets.GITHUB_TOKEN }}
          package-name: practica1-grupo1
          target-ros2-distro: rolling
          vcs-repo-file-url: ""
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 4
              }
            }
